### ISSUE TITLE
Passenger vehicle UI issue with addon enabled

### ISSUE THREAD

**Issue by Xorag** [d4kir92/MoveAny#22] opened 2023-07-18 20:02 UTC
I've noticed an issue the past few weeks where the passenger vehicle UI for the grand travelers tundra mammoth appears to be pushed near the middle of the screen, however when the addon is disabled, it goes back to the right edge of the screen:

Enabled:
![image](https://github.com/d4kir92/MoveAny/assets/42698965/b59d98c5-5e7d-4132-8044-5f5eb605182d)

Addon disabled:
![image](https://github.com/d4kir92/MoveAny/assets/42698965/ab970be2-4826-4de5-bbea-b0d48fa2050b)

**Comment by Xorag** [comment] 2023-07-18 20:03
Note that I have not customized the location of this frame with the addon nor the in-game edit mode

**Comment by Xorag** [comment] 2023-07-18 20:14
Also this does not happen with other mounts like the X53-Touring Rocket

**Comment by d4kir92** [comment] 2023-07-19 20:17
is this fixed in v1.5.10+?

**Comment by Xorag** [comment] 2023-07-19 22:51
![image](https://github.com/d4kir92/MoveAny/assets/42698965/5e11c7fa-ed57-4f79-b1a8-1e6264bcd88a)

**Comment by Xorag** [comment] 2023-07-19 22:52
my only configured moved frames are target cast bar and target of target, and totem ui is hidden

**Comment by d4kir92** [comment] 2023-07-20 04:57
this may can caused by editmode when it is attached to something that grows

if you want a fixed position you need to move it in editmode or force it with moveany

**Comment by d4kir92** [comment] 2023-07-20 04:57
some elements are "parented" to another frame, so it may move with the "parented"

**Comment by d4kir92** [comment] 2023-07-20 05:57
please try v1.5.12+

**Comment by Xorag** [comment] 2023-07-20 18:18
yes its fixed! thanks!

**Closed** 2023-07-20 18:19 UTC
